### ISSUE TITLE
Tracking issue for the changes for game version `1.21`

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/vanilla-mcdoc#13]
```[tasklist]
### New `minecraft:resource`
- [x] `painting_variant` in `/data/variants`. Resolved in [81bd4a5](https://github.com/SpyglassMC/vanilla-mcdoc/commit/81bd4a5eddc16bf358ac48bd94832856d4e9e407)
- [x] `jukebox_song` in `/data/variants`. Resolved in [9ac13a6](https://github.com/SpyglassMC/vanilla-mcdoc/commit/9ac13a62e49c3f79e1784815708ef0fe1e19d457)
- [x] `enchantment` in `/data`
```
```[tasklist]
### New `minecraft:data_component`
- [x] `jukebox_playable` in `DefaultItemComponents`. Resolved in [9ac13a6](https://github.com/SpyglassMC/vanilla-mcdoc/commit/9ac13a62e49c3f79e1784815708ef0fe1e19d457)
```

```[tasklist]
### Changed NBT
- [x] Update entity attributes
```

**Comment by MulverineX** [comment]
(there's missing changes here that were done already, but I'm just going to close this as-is)
