### ISSUE TITLE
Ensure all inline codec shorthands are supported

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/vanilla-mcdoc#14]
```[tasklist]
### Tasks
- [ ] Painting entity data
- [ ] Trims (yes, in 1.20.5 too)
- [ ] Goat Horns (yes, in 1.20.5 too)
- [ ] Find more :concern:
```

**Comment by MulverineX** [comment]
Honorable mention: jukebox song sound events. It appears that mojang hardcodes `range` for these, because custom sound events require an object to wrap the sound event id. 

https://github.com/SpyglassMC/vanilla-mcdoc/blob/9ac13a62e49c3f79e1784815708ef0fe1e19d457/java/data/variants/jukebox_song.mcdoc#L8

**Comment by Nico314159** [comment]
Hmm, it might be helpful to have a `not` in the type syntax. So you could do `float not 0` instead of using a really small number for the range minimum

**Comment by MulverineX** [comment]
I mean they're also not negative, so it may be more realistic to have built-in literal variables.

`float @ %MIN_POS_FLOAT..`

**Comment by misode** [comment]
mcdoc supports exclusive ranges: `float @ 0<..`
<https://spyglassmc.com/user/mcdoc/#number-range>
